### PR TITLE
Add cookie parser dependency

### PR DESCRIPTION
**Pull request by hurracrane**

### CODE REVIEW

**Comment by ruyadorno** [comment]
yo @zeachco I helped @hurracrane putting together these PRs so that we can have support to parsing cookies from the currently exposed express requests in the mocks (some features on appdirect are actually stored on cookies, such as the current language)

ideally a way to expose the express server itself (the `app` from `server/app.js` is probably more desirable since that will give us full flexibility to add whatever middleware we might need.

anyways, I still think it's worth merging these two PRs (this and #15) as supporting cookies is a feature that might be widely needed. The [cookie-parser](https://www.npmjs.com/package/cookie-parser) middleware is referred to as the recommended way of parsing cookies in the [express docs](http://expressjs.com/en/4x/api.html#req.cookies) (I think it's one of middlewares they break up into smaller modules later on and separated from the express core)

can we have a merge asap? @hurracrane is gonna need a full day until the artifactory cache cleans up :( sorry for not pinging you about this earlier, have been in a big rush before leaving on vacation

**Comment by zeachco** [comment]
Looks good to me but is there a reason it's separated in too PRs :smile: ?

**Comment by ruyadorno** [comment]
I'll name it pr-opened-from-github-web-interface-mayhem 😂

**Comment by zeachco** [comment]
oh I see, LOL

**Comment by ruyadorno** [comment]
the tests on the other pr should pass once the package.json dep is merged... I guess...

**Comment by zeachco** [comment]
ok because of the artifactory caching i'll merge this and fix later if some :bomb: happens
otherwise, know that you have access to merge it as well @ruyadorno :smile:

**Comment by ruyadorno** [comment]
ooohh, true that! 👍 had completely forgotten! good to know 😄

**Comment by ruyadorno** [comment]
thanks 🎉

**Comment by hurracrane** [comment]
@ruyadorno @zeachco niicceee!  Thanks guys!

**Pull request merged**
